FROM nginx
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# 1. Use an official Nginx image as base
# 2. Copy your HTML file into Nginx's default web directory
# 3. Expose container port
# 4. Start Nginx in the foreground